### PR TITLE
Add schema support to MS SQL Server

### PR DESCRIPTION
**Pull request by ovoronyi**
Add schema support to MS SQL Server.

### CODE REVIEW

**Comment by ovoronyi** [comment]
Hi @markstory, thanks for reviewing my merge request. It was closed. Could you share the reason? I'd like to understand and improve for future contributions. Thanks!

**Comment by dereuromark** [comment]
This was closed by GitHub itself, after he removed the 4.next branch and readded it.
I am sure you could reopen it again.

That said: You might want to rebase so only your commit is visible in the PR.

**Comment by ovoronyi** [comment]
@markstory thank you for the quick response! Got it – I’ll rebase and create a new PR.

**Comment by dereuromark** [comment]
I am not him the great^^

**Comment by ovoronyi** [comment]
Sorry @dereuromark, my mistake – it’s Friday, you know! :)

**Pull request closed without merging**
