### PR TITLE
Update the tests so they pass again following the release of phinx 0.4.6

### PR DESCRIPTION
**Pull request by HavokInspiration**
**This should not be merged right now**

This phinx release and this PR shed some light on some migrations tests that were not done. Now that they are all running, I spotted a bug in phinx implementation of the mechanism to drop foreign key constraints with SQLite. I submitted a PR on phinx repo : https://github.com/robmorgan/phinx/pull/641

The test suite will be failing for SQLite until the change I will propose will be merged and a new phinx release is 

-----------------------

This phinx release introduced changes in the naming scheme the migration files / the migration classes should follow, breaking the tests.

This commit also removes the ``update()`` call after the ``dropForeignKey()`` calls : it was not necessary.

### CODE REVIEW

**Comment by HavokInspiration** [comment]
I pushed a new commit that contains a few things.

First of all, since nothing has moved on phinx's side, I decided to implement a temporary fix to fix the cause of the tests failures with SQLite. I'll remove it once (and if) the PR on phinx repo is merged.

While doing that, I noticed a defect : the Migrations class was not using the CakeAdapter but the Adapter from phinx which prevented the bugfix to fix anything. So I fixed this along the way.

Tests should be passing again now.

**Comment by HavokInspiration** [comment]
PR has been merged. We just need a release now. I updated the code to remove the temp fix I added.

**Comment by HavokInspiration** [comment]
So this can be merged and we can move on, I was thinking about changing the composer config so it downloads the latest state of the phinx master branch (well the 0.4.x-dev) where the necessary fix are.
Any thoughts about this ?

**Comment by HavokInspiration** [comment]
I pushed a commit where I change the dependency for phinx to ``dev-master``. This way we have the merged changes from phinx and we can move on with this PR, #125, #62, target the min requirement for cake to 3.1 and start working on #128. 

What do you think ?
This could be reverted when a new release of phinx is done.

**Comment by lorenzo** [comment]
I think that plan makes sense @HavokInspiration

**Pull request merged**
