### PR TITLE
Failing calls to the Shell now return a proper exit code

### PR DESCRIPTION
**Pull request by HavokInspiration**
Refs #215

### CODE REVIEW

**Comment by thinkingmedia** [comment]
Have you tested this? I've found that cake ignores the return value for main in a shell. I had to use `exit($value)` to get me shells to return a value.

**Comment by HavokInspiration** [comment]
It does. See [this](https://github.com/cakephp/app/blob/master/bin/cake.php#L33).
The key is to return a bool (true if success, false if error) because of [how the ShellDispatcher treats the response of the inner method call](https://github.com/cakephp/cakephp/blob/master/src/Console/ShellDispatcher.php#L178-L189).

You can clone the branch, run a shell without error and run ``echo $?`` it should return 0.
Create an error (remove an entry in the phinxlog for instance) and run ``echo $?`` it should return 1.

And given than shell can be dispatched from other shell, using exit is not an option. Whether or not to early exit the entire shell call should come from the user and not the plugin itself.

**Comment by thinkingmedia** [comment]
Ah, okay. I was trying to have the shell return an exit code as a value (i.e. how many records exist). Which doesn't work because mutates the return value to 0 or 1.

I don't think that will effect your changes.

**Comment by HavokInspiration** [comment]
> I don't think that will effect your changes.

What do you mean ?

**Comment by HavokInspiration** [comment]
Anyone to give this a quick review ?

**Comment by dereuromark** [comment]
Looks good to me.

**Pull request merged**
