### PR TITLE
Fix glob pattern escaping.

### PR DESCRIPTION
**Pull request by dereuromark**
The `.` would otherwise be "any" char afaik.

### CODE REVIEW

**Comment by dereuromark** [comment]
Windows is failing, is it possible that it behaves differently here?

**Comment by markstory** [comment]
Isn't `\` the directory separator in windows and not an escape char?

**Comment by dereuromark** [comment]
So do we just ignore it (close PR), or what do you suggest as fix?

**Comment by markstory** [comment]
> So do we just ignore it (close PR), or what do you suggest as fix?

I think we ignore. While `.` matches any character in regex, I don't think that is true for glob expressions.

**Comment by dereuromark** [comment]
Hm, in those cases it would work, yeah.

But we also merged https://github.com/cakephp/migrations/pull/773/files#diff-95ee3850797051650617a77bbc9cb2f047a0ce5997f32ce2582a5d9df8253fb0R74 in
and there without it it could become false positive or things maybe.
I wish there was a way to escape so it works for both.

**Pull request closed without merging**
