### PR TITLE
Fix #289

### LINKED ISSUE #289: [Bug] Impossible to set `null` to true + trailing `?` when we specify the length param too within the bake migrate command
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What i did
Tried this bake migration cmd:
```bash
bin/cake bake migration CreateServices "title:string?[50]"
```

### Expected Behavior
```php
use Migrations\AbstractMigration;

class CreateServices extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function change()
    {
        $table = $this->table('services');
        $table->addColumn('title', 'string', [
            'default' => null,
            'limit' => 50,
            'null' => true,
        ]);
        $table->create();
    }
}
```

### Actual Behavior
```php
use Migrations\AbstractMigration;

class CreateServices extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function change()
    {
        $table = $this->table('services');
        $table->addColumn('title', 'string?', [
            'default' => null,
            'limit' => 50,
            'null' => false,
        ]);
        $table->create();
    }
}
```

### Fix
cakephp/migrations/src/Util/ColumnParser.php:
```php
public function parseFields($arguments)
{
    $fields = [];
    $arguments = $this->validArguments($arguments);
    foreach ($arguments as $field) {
        preg_match($this->regexpParseColumn, $field, $matches);
        $field = $matches[1];
        $type = Hash::get($matches, 2);
        $indexType = Hash::get($matches, 3);

        $typeIsPk = in_array($type, ['primary', 'primary_key']);
        $isPrimaryKey = false;
        if ($typeIsPk || in_array($indexType, ['primary', 'primary_key'])) {
            $isPrimaryKey = true;

            if ($typeIsPk) {
                $type = 'primary';
            }
        }
 
        // $nullable = substr($type, -1) === '?';
        $nullable = (bool)preg_match('/\w+\?(\[\d+\])?/', $type);
        // $type = $nullable ? substr($type, 0, -1) : $type;
        $type = $nullable ? str_replace('?', '', $type) : $type;

        list($type, $length) = $this->getTypeAndLength($field, $type);
        $fields[$field] = [
            'columnType' => $type,
            'options' => [
                'null' => $nullable,
                'default' => null,
            ]
        ];

        if ($length !== null) {
            $fields[$field]['options']['limit'] = $length;
        }

        if ($isPrimaryKey === true && $type === 'integer') {
            $fields[$field]['options']['autoIncrement'] = true;
        }
    }

    return $fields;
}
```

### PR DESCRIPTION
**Pull request by flashios09**
Fix #289

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Hi and thanks for the pull request !
Current tests are passing which is a really good thing.

Would you mind adding new tests to cover the improvements you introduce ?

**Comment by flashios09** [comment]
@HavokInspiration this can be tested only via cake console command 

Before the test was only for **the last char === ?** so this will set **$nullable** to **true/false** and remove the **?** from the **$type**
```php
// check if the last char is `?`
$nullable = substr($type, -1) === '?';
// if true remove the `?` from $type
$type = $nullable ? substr($type, 0, -1) : $type;
```
this works on those cases:
1. "integer"(or any other valid type)
2. "integer?"

but not on this case:
- "integer?[10]"  

because the last char is **]** even if we have the **?**
What i have done:
replace the test with a regex `'/\w+\?(\[\d+\])?/'` to match the **?**:
Match any word chars `\w+`, match the **?** char `\?`, match the length(zero or one time) `(\[d+\])?`

**Comment by dereuromark** [comment]
@flashios09 
The parseFields() method should be unit testable - so this specific case is then protected regarding regressions.
You can mock everything not relevant for it.

**Comment by HavokInspiration** [comment]
They already are [tests for the `ColumnParser` class](https://github.com/cakephp/migrations/blob/master/tests/TestCase/Util/ColumnParserTest.php) and especially for the [nullable field feature](https://github.com/cakephp/migrations/blob/master/tests/TestCase/Util/ColumnParserTest.php#L114-L149)

But I can write the tests and when they are ready, I'll merge your PR if you prefer.

**Comment by flashios09** [comment]
@HavokInspiration can you please take a look at this issue #286  too and tell me what do you think

**Comment by josegonzalez** [comment]
@flashios09 probably worth fixing #286 in a separate PR :)

**Comment by HavokInspiration** [comment]
Thanks @flashios09 :+1:

**Pull request merged**
