### PR TITLE
Revert "Add message if migrations/seeds folders do not exist and debug is dis…"

### PR DESCRIPTION
**Pull request by othercorey**
Reverts cakephp/migrations#584

Testing this PR is causing the test failures.

### CODE REVIEW

**Comment by othercorey** [comment]
@ajibarra Can you look into this?

**Comment by ajibarra** [comment]
> @ajibarra Can you look into this?

@othercorey I am out of the office until Monday. I am not able to see what is actually failing directly on the phone.

**Comment by othercorey** [comment]
> > @ajibarra Can you look into this?
> 
> @othercorey I am out of the office until Monday. I am not able to see what is actually failing directly on the phone.

Just check the failures on the last commit when you can.

**Comment by ajibarra** [comment]
@othercorey I have sent a new MR to fix unit tests. Please take a look to #592. If everything is okay we could close this one. Please let me know. Thank you!.

**Pull request closed without merging**
