### PR TITLE
fix issue with field name starting with a delimiter

### PR DESCRIPTION
**Pull request by antograssiot**
ref #147

### CODE REVIEW

**Comment by antograssiot** [comment]
the failling tests are not related...

**Comment by lorenzo** [comment]
I wonder where test broke

**Comment by HavokInspiration** [comment]
@lorenzo I suspect from here https://github.com/robmorgan/phinx/pull/671/files but I can't run tests right now to confirm it.

**Comment by antograssiot** [comment]
@HavokInspiration that was my first guess but it hasn't been merged in master yet...

**Comment by HavokInspiration** [comment]
@antograssiot The branch 0.4.x-dev is considered master with phinx. So this is probably the root cause of the issue.

**Comment by antograssiot** [comment]
@HavokInspiration Ah ok, I was pretty sure that you would need to require dev-0.4.x-dev as listed on packagist to get the latest 0.4 but I might be totaly wrong.

**Comment by HavokInspiration** [comment]
Using ``dev-master`` fetch from ``0.4.x-dev`` (if you go on phinx repo and check the default branch, you'll notice that it is not ``master``) (this is at least what I observed when I changed the dependency version to ``dev-master`` when two fixes I added were merged in ``0.4.x-dev`` but not released)

**Comment by HavokInspiration** [comment]
I investigated the tests failure but I was not able to reproduce them (either on my local setup at home and on a VM I use at work).
The errors were suppressed with a recent PR though.

**Pull request merged**
