### PR TITLE
fixed:  hierarchy of namespace in plugin name

### PR DESCRIPTION
**Pull request by zoghal**
fixed:  hierarchy of namespace in plugin name

### CODE REVIEW

**Comment by lorenzo** [comment]
Would you be able to provide a test for this?

**Comment by zoghal** [comment]
really need to test? 
this  \Cake\Core\ConventionsTrait::_pluginNamespace()  in core package & and very used in bake plugin(https://github.com/cakephp/bake/commit/ad36ef57ff1403c1a32dea266a56d4f283ff8bd0) .

Of course I tried but :-1:

**Comment by josegonzalez** [comment]
Yes, you need to add a test - they aren't hard, take a look at the existing comparison ones - as otherwise it'll be pretty easy to break this and then not catch the breakage until later.

Also you have some PHPCS issues.

**Comment by zoghal** [comment]
@josegonzalez  ok i retry again

**Comment by zoghal** [comment]
@lorenzo Overall, I forgot this PR :(, sorry and thanks :)

**Pull request merged**
