### PR TITLE
Phinx 0.5.2

### PR DESCRIPTION
**Pull request by deizel**
- [x] Fixes missing interface method (#202) (added in https://github.com/robmorgan/phinx/compare/v0.5.1...v0.5.2)
- [x] Adds support for following features: https://github.com/robmorgan/phinx#version-history

### CODE REVIEW

**Comment by HavokInspiration** [comment]
I was working on adding support for 0.5.2 and implementing the new status output (and adding tests for it) as well as adding support for fulltext index for MySQL.

It is almost ready, I just have to tune the new build for MySQL 5.6 a bit to pass (since there is support for fulltext index on innodb only from 5.6 and upward and Travis runs 5.5 by default).

See the diff : https://github.com/cakephp/migrations/compare/master...HavokInspiration:phinx-0.5.2

**Comment by HavokInspiration** [comment]
Merged it. I'll build my additions on top of it.

**Comment by deizel** [comment]
Thanks @HavokInspiration and sorry for jumping the gun - I had forked this and phinx to get some features I needed, so figured I would submit PR instead of leaving it on my own fork. ;)

I had looked briefly at implementing `getVersionLogs` into the existing status command, but figured it was enough work to require it's own PR - glad to hear you are on it already! :clap:

**Comment by HavokInspiration** [comment]
Don't worry, everything is going forward at the end of the day.

Out of curiosity, what features did you needed ?

**Comment by deizel** [comment]
Good stuff - for now it was the `JSON` data type and https://github.com/robmorgan/phinx/pull/768 to avoid hacks like [this](https://gist.github.com/adayth/f0ead7bd210e3968208e#gistcomment-1585602).

**Comment by HavokInspiration** [comment]
Yes, I'm waiting for https://github.com/robmorgan/phinx/pull/768 as well.
If you need to, you can currently do it like this : 

```php
use Migrations\AbstractMigration;

class CreateProductsTable extends AbstractMigration
{

    public $autoId = false;

    public function up()
    {
        $table = $this->table('products');
        $table
            ->addColumn('id', 'integer', [
                'autoIncrement' => true,
                'signed' => false,
                'limit' => 11
            ])
            ->addPrimaryKey('id')
            ->addColumn('name', 'string')
            ->addColumn('description', 'text')
            ->create();
    }
}
```

**Pull request merged**
