### PR TITLE
Switch to codecov

### PR DESCRIPTION
**Pull request by HavokInspiration**

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Is there anything to do on the repo to activate the report on PR ? If so, I need someone with the necessary rights to do so. I was able to activate the repo cover in codecov.io though.

**Comment by bravo-kernel** [comment]
I'm having the same issue: *no reports found for master" even though I successfully merged the PR containing the switch to codecov so.... please share if you manage to solve this.

**Comment by bravo-kernel** [comment]
Found it, seems this codecov requires uploading reports and in our case the master report has not been generated and uploaded yet. I solved it by running this from the command line inside my plugin directory:

```bash
composer install
 phpunit --coverage-clover=coverage.xml
 bash <(curl -s https://codecov.io/bash) -t <MYTOKEN>
```
Obviously reverse engineered from the travis.yml but hey, feels good nevertheless :relaxed:

**Comment by HavokInspiration** [comment]
@bravo-kernel Thanks for sharing. It worked like a charm.
I still can't get the coverage report to show up in the PR checks though.

**Comment by lorenzo** [comment]
let's see if merging this fixes the missing notification on the next PR

**Pull request merged**
