### PR TITLE
Re-add the tests against the lower php deps

### PR DESCRIPTION
**Pull request by antograssiot**
They were removed while getting rid of php5.4

Also added PHP 7.1 like in other repos

### CODE REVIEW

**Comment by HavokInspiration** [comment]
Apparently we are not compatible with the lowest PHPUnit dependency that can be found 🤔 
I added a commit to increase the minimum dependency of PHPUnit to see if it corrects a part of the build.

**Comment by HavokInspiration** [comment]
The build is going further. The error we now have is because the `Shell::abort()` method was added in 3.2.0 and the min dependency loads CakePHP 3.1.0.

We have two solutions :

- we bump up the minimum CakePHP requirement to `~3.2`
- we change the way the error is raised.

**Comment by HavokInspiration** [comment]
The build is going further. The error we now have is because the `Shell::abort()` method was added in 3.2.0 and the min dependency loads CakePHP 3.1.0.

We have two solutions :

- we bump up the minimum CakePHP requirement to `~3.2`
- we change the way the error is raised (and the related tests).

I'd go for bumping the CakePHP requirement.

**Comment by dereuromark** [comment]
3.2 min seems fine to me. Other Plugins will require 3.4 even soon.

**Comment by antograssiot** [comment]
So I guess this check was necessary after all...

**Comment by HavokInspiration** [comment]
I pushed some commits that should fix the build.

**Comment by HavokInspiration** [comment]
Well, what do you know, it even increased coverage.

**Comment by lorenzo** [comment]
Nice job!

**Pull request merged**
