### PR TITLE
Fix deprecations.

### PR DESCRIPTION
**Pull request by dereuromark**
Psalm

> ERROR: DeprecatedClass - src/Table.php:153:9 - Cake\ORM\TableRegistry is marked deprecated (see https://psalm.dev/098)
        TableRegistry::getTableLocator()->clear();
ERROR: DeprecatedClass - src/TableFinderTrait.php:175:18 - Cake\ORM\TableRegistry is marked deprecated (see https://psalm.dev/098)
        $table = TableRegistry::getTableLocator()->get($className);

And invalid namespaces will break in Composer v2

### CODE REVIEW

**Comment by dereuromark** [comment]
@cakephp/core Anyone wants to review?

**Comment by ADmad** [comment]
The test failures are unrelated?

**Comment by dereuromark** [comment]
I think the tests started failing with 4.1 release of Cake core
I added a cronjob based travis run to make sure we catch those earlier now, we should do the same for all other core plugins / repos IMO.

**Comment by markstory** [comment]
I'll get the failing tests fixed later this week.

**Pull request merged**
