### PR TITLE
Update phinx version to 0.6.x

### PR DESCRIPTION
**Pull request by hiromi2424**
This PR will contain updates of phinx's version (and maybe fixes for it).
WIP now.

### CODE REVIEW

**Comment by dereuromark** [comment]
Any update here? Does this version work with the Migrations plugin?

**Comment by hiromi2424** [comment]
no. replacing version effects widely.
gave up:(

**Comment by HavokInspiration** [comment]
That's on my to-do list. But I'll clean the bug tickets (and fix the unusual Postgres build error) before taking care of that.

**Comment by HavokInspiration** [comment]
Closing in favor of #291 which updates to 0.6.5 with all tests passing.
Thanks for your contribution @hiromi2424 ! :smile:

**Comment by hiromi2424** [comment]
@HavokInspiration Grdat work! 
I'd have not done contribution but you you'd

**Comment by hiromi2424** [comment]
@HavokInspiration Grdat work!
I'd have not done contribution but you you'd done it. Thank you 💗

**Pull request closed without merging**
