### PR TITLE
Using Shell::abort instead of error as it is deprecated

### PR DESCRIPTION
**Pull request by LubosRemplik**

### CODE REVIEW

**Comment by saeideng** [comment]
you need to add 
```php
        $this->expectException(...);
        $this->expectExceptionMessage(...);
```
into related tests

**Comment by LubosRemplik** [comment]
Thanks for the hint, there is one more error with unit test, any ideas?

**Comment by markstory** [comment]
@LubosRemplik looks like an exception type has changed.

**Comment by LubosRemplik** [comment]
Somehow `MigrationTask` needs to be mocked with `error` method set so I have added to pass unit tests, but if someone can review that would be great as I am not sure with changes :)

**Pull request merged**
