### PR TITLE
Static analysis

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
"8 errors found" left

**Comment by ADmad** [comment]
Getting rid of those errors required fixing bake which I had done https://github.com/cakephp/bake/pull/687/files#diff-58c098d23102800f39f0c89bf6ddaf06R44.

So they will be gone once a new bake release is done.

**Comment by dereuromark** [comment]
After phpstan release we have now one issue more:
```
Line   Command/BakeMigrationDiffCommand.php                   
 ------ ------------------------------------------------------- 
  542    Call to an undefined method                            
         Cake\Datasource\ConnectionInterface::cacheMetadata().  
 ------ ------------------------------------------------------- 
```

**Comment by ADmad** [comment]
I took care of the new error.

**Comment by dereuromark** [comment]
Thanks a lot!

**Pull request merged**
